### ISSUE TITLE
CRC32?

### ISSUE THREAD

**Issue by sprite-1** [namazso/OpenHashTab#1]
Can you add CRC32 to the list the list of calculated values?

**Comment by namazso** [comment]
yes, however unfortunately SVF files don't follow the sumfile format, so those need some work. Although I'm not sure if i'd want the green highlights for them even if they were supported, since CRC isn't cryptographically secure

**Comment by sprite-1** [comment]
You can also make it an optional thing that is turned off by default

**Comment by namazso** [comment]
Considering I already have some other algorithms implemented (just commented out) that were considered too slow or insecure, adding a new one like CRC is quite easy (in fact I'll probably add 64 bit one too).
I think I will add a configuration dialog for selecting algorithms, whether they should be considered secure (insecure matches will be marked by some other color, and noted as a different number in the Done text)
With this I can also include the currently disabled algorithms (RipeMD160, BLAKE2sp, SHA3) although I'll set them as default-disabled

Unfortunately making dynamic dialog elements isn't really that easy in Windows so I'm yet to figure out how to make a config dialog that isn't hard to use and / or ugly.
The hasher part is also fit for a refactoring using proper C++, since currently its just  a really slim mbedTLS wrapper

**Comment by sprite-1** [comment]
I mean even without a proper dialog, even a registry key or an `*.ini` file could probably suffice in the meantime (though not the best for user experience)

As for the security of the hash, I personally only use CRC32 for some small personal stuff where collisions are very unlikely to happen, In fact, I would be fine with only having CRC32 and MD5 active if that would make the display of results faster. Although IDK how much of performance boost that will have if the file's already been loaded already anyway.

Of course, everything is up to your discretion, I'm just throwing ideas around

**Comment by namazso** [comment]
Throughput equals the slowest algorithm's throughput as long as you have at least as much CPU threads as enabled hash algorithms (which is 4 currently for this very reason, since [Steam Hardware Survey](https://store.steampowered.com/hwsurvey/) says that roughly 76% of people have 4 or more cores)

Of the current algorithms SHA-512 is the slowest, with throughput of 700 MB/s on my machine. MD5 measures at 750 MB/s on my machine, therefore disabling everything but MD5 would give you roughly 7% speed boost (given that you have at least 4 cores, else more).

Anyways, I was working on changing things around and added a few algorithms and a configuration dialog:
https://streamable.com/awt3v
configs are saved per-user in registry

I'm still cleaning up some stuff before next release, so if you have any suggestions for this, feel free to write them here

**Comment by sprite-1** [comment]
Maybe a context menu on the hash list for the highlighted line(s) to either copy just the hash part or including the algorithm names

![image](https://user-images.githubusercontent.com/33685433/74032883-f8e52680-49ef-11ea-964a-7148aa2ec341.png)

**Comment by namazso** [comment]
You can already do that:
doubleclick the hash to copy it
doubleclick the file or algorithm name to copy filename and hash in sumfile format

**Comment by sprite-1** [comment]
> edit: on a second though, maybe I should write about this in the readme or something
I agree, I didn't even know that was a thing

> You can already do almost that
Yeah but for discoverability's sake I assume most people would try to right click something if they wanted to copy it, plus, double clicking doesn't work for multi-selected lines

**Comment by namazso** [comment]
Hm, seems like this is a new use case, I never thought anyone would want different algorithms results for the same file, hence the doubleclicking and sumfile format (since if you just want the hashes for all files, there is the `To clipboard` button).

I think I'll just make it copy the selected ones in `name<tab>algorithm<tab>hash<newline>` format on rightclicking, mainly because it's faster to use, faster to develop, and everything else can be done already. I can also avoid localization like this. As for discoverability, one will probably notice the clipboard being overwritten soon enough. Or maybe i could post a message in the `Done!` field (also for doubleclicks), maybe temporarily so the done text isn't lost.

**Comment by sprite-1** [comment]
Yeah that seems to be a good compromise IMO, just add it to the right click directly without a context menu, and have something indicate `Done`

**Comment by namazso** [comment]
added in v2.0.0
