### ISSUE TITLE
Feature Request: adding progress bar 

### ISSUE THREAD

**Issue by Remonli** [namazso/OpenHashTab#11]
When hashing large files, it will be more clear if we have a progress bar or text indicator :10%,20%.... 
Is it possible to add this feature ? 

Thanks for your great work.

**Comment by namazso** [comment]
I thought about adding this before, but due to the quite heavy parallelization it isn't trivial. I'll see if i can somehow add it without massive changes.
Also note that up to 1 GB of reads can be pending (if you have many files added), so it might not always be reporting all that accurate

**Comment by Riajyuu** [comment]
@namazso You may learn this from 7-zip software, aka two progress bar:
the top one indicates progress of  current algorithm, and the bottom one for overall progress.
The benefit is that the first does not need to be that accurate.

**Comment by namazso** [comment]
@Riajyuu 7-zip does the files in order (also, top bar is file and not the algorithm iirc). OpenHashTab doesn't, up to 512 files are progressed simultaneously, so pretty much anything but a size-based single bar is out of the question.
Additionally, the problem is that progress is made in a random worker thread in the pool, and we can't just spam the main window with events because that'd kill performance (and FileHashTask doesn't even know if a window still exists or not). So we need some intermediate that thread-safely accumulates progress, and occassionally sends a window message when visible progress is made.

**Comment by namazso** [comment]
![ZOp8eF0QTx](https://user-images.githubusercontent.com/8676443/77368975-c6a04600-6d5d-11ea-84ed-42457cb80278.gif)

does this look good?

**Comment by Riajyuu** [comment]
I believe the process bar should be hidden as soon as complete

**Comment by Remonli** [comment]
It looks great, and I agree with @Riajyuu ,it's better to hide it when complete hashing.

In the meantime, did you notice my replie on https://github.com/namazso/OpenHashTab/issues/4 ? 
I'm not sure as the issue was closed, but I think it could be improved a little.

**Comment by zhudock** [comment]
That preview looks fantastic!

**Comment by JustMyGithub** [comment]
> 
> 
> @Riajyuu 7-zip does the files in order (also, top bar is file and not the algorithm iirc). OpenHashTab doesn't, up to 512 files are progressed simultaneously, so pretty much anything but a size-based single bar is out of the question.
> Additionally, the problem is that progress is made in a random worker thread in the pool, and we can't just spam the main window with events because that'd kill performance (and FileHashTask doesn't even know if a window still exists or not). So we need some intermediate that thread-safely accumulates progress, and occassionally sends a window message when visible progress is made.

Sorry, this is off the major topic here, but how is "up to 512" chosen? This should a massive performance drawback on a HDD ans may also negaitvely impact other tasks on a SSD?!

**Comment by namazso** [comment]
@JustMyGithub it was chosen because each task gets 2 MB read buffer space, so this accounts for 1 GB memory usage which is a good tradeoff. When developing I found just throwing 512 read requests at windows was easier. Also note that everything is written async, it's not me chosing the amount of actual workers but windows. And yes you're correct on the HDD drawback, it would need a separate scheduling that does files one-by-one. There's code to read and tell apart volume indices which was meant for this, however it's not as easy as a switch since a single hash task may involve bits from both SSDs and HDDs at the same time.

**Comment by namazso** [comment]
Included in newest release.
