### ISSUE TITLE
Feature Request: Sort results

### ISSUE THREAD

**Issue by bluelayer** [namazso/OpenHashTab#12]
hello!

I just love this tab but I really miss the ability to sort results, can be made?

Thanks!

**Comment by namazso** [comment]
I'm working on changing the hash listview into a treelistview, like this:

![image](https://user-images.githubusercontent.com/8676443/77918547-54b78780-729c-11ea-951c-b5f11a730b12.png)

I hope you didn't plan on sorting by algorithm, because I don't think I can support that in the planned treelistview.

**Comment by bluelayer** [comment]
well, i just want to sort the lines because I manage a 6000~ file list, when I have one or two problems it's really hard to find them.
