### ISSUE TITLE
No color coding in Windows 11

### ISSUE THREAD

**Issue by Alexander-Serov** [namazso/OpenHashTab#127]
All corresponding options seem to be active, but the matches are not highlighted. Could you tell me if this is a bug or I'm missing something?
![image](https://user-images.githubusercontent.com/22743277/175946057-472b9a1e-2449-40fd-9d6a-808bec77e8f1.png)

![image](https://user-images.githubusercontent.com/22743277/175946104-5b67e036-051e-466f-bd1b-c4c66046e2dc.png)

**Comment by namazso** [comment]
This is by design, the checker field reports results below the field:

![image](https://user-images.githubusercontent.com/8676443/175947456-c7745a98-d7ab-4e08-8f8d-54c83d36c065.png)

The color coding is for the sumfile checking operation mode. Export the hashes to a file then open the output, and you'll see what I mean.

**Comment by Alexander-Serov** [comment]
Thank you, I was confused by this screenshot which looked the same!
https://github.com/namazso/OpenHashTab/blob/master/resources/screenshot.png
We can close then.
