### ISSUE TITLE
Summarize results

### ISSUE THREAD

**Issue by VsevolodGolovanov** [namazso/OpenHashTab#149]
OpenHashTab just says "Done!" and shows me a table of results per file - I don't want to manually scroll and check through thousands of files. There should by a summary, like in HashCheck:
![image](https://user-images.githubusercontent.com/8070317/198275001-61e5db72-129c-4822-a3ed-97c97c55d828.png)

**Comment by VsevolodGolovanov** [comment]
I had to do a few tests to realize that "Done!" really means no missing files and no mismatches. This should be explicitly stated.

![image](https://user-images.githubusercontent.com/8070317/198276534-96716fa1-79c2-4c17-b694-7af00f794c05.png)
Also without testing it's not obvious what the numbers in the braces mean. Their meaning is also better explicitly stated like in HashCheck.

**Comment by VsevolodGolovanov** [comment]
Summary should probably have matched, mismatched, unreadable, remaining and total file counts. No need to repeat "of <total>" each time like HashCheck.

**Comment by namazso** [comment]
well, the problem is that the GUI is already pretty crowded. I tried some different arrangements like this:

![image](https://github.com/namazso/OpenHashTab/assets/8676443/71670fea-1e69-4827-8559-dca52d5b74e4)

(obviously would be color coded if it was finished)

The problem is that's too far from the main listing for people to make the connection.

I *could* shrink the results listing, but that is already concerningly small for multiple files.

Another idea would be turning the "Interpreted as sumfile" into an icon or something (and reuse the space it currently occupies), but I can't really come up with a good way to signal that.

**Comment by namazso** [comment]
Maybe I could just use the main icon as the indicator, and just add a tooltip that holds the current (Interpreted as sumfile) message
