### ISSUE TITLE
Feature request. Hiper link to virustotal

### ISSUE THREAD

**Issue by avgsandeep** [namazso/OpenHashTab#15]
Hi awesome guys, it would be nice to gave hash/file name click able to open virustotal site, if not possible please color codes it green if file found on virustotal 0/60

**Comment by namazso** [comment]
both should be possible, I'll see how much changes this would require, but I certainly won't make this default since it does network comms.
Note that VT can only search by MD5 / SHA1 / SHA256, so that will be a requirement in any case. I'm not sure if I should allow searching by MD5 since it's considered insecure, a false negative would be much worse than just nagging the user to enable SHA1 or SHA256.

**Comment by namazso** [comment]
an initial implementation for querying virustotal has been added
![image](https://user-images.githubusercontent.com/8676443/100579381-6ac28f80-32e4-11eb-9c5d-d1c839ba3108.png)
