### ISSUE TITLE
x64 Windows version

### ISSUE THREAD

**Issue by Neustradamus** [namazso/OpenHashTab#163]
Hi @namazso,

It is possible to create the x64 Windows version?

Currently it is in x86 only.

Thanks in advance.

**Comment by namazso** [comment]
> Currently it is in x86 only.

No it isn't. The installer will install the correct version. The fact that it works at all shows it's the right architecture, as only matching architecture can work as a shell extension.

**Comment by Neustradamus** [comment]
@namazso: I have tested on a Windows x64 machine, it has been installed in "C:\Program Files (x86)\OpenHashTab\"
- AlgorithmsDll-x64-avx.dll
- AlgorithmsDll-x64-avx2.dll
- AlgorithmsDll-x64-avx512.dll
- AlgorithmsDll-x64-sse2.dll
- OpenHashTab.dll
- unins000.dat
- unins000.exe

**Comment by namazso** [comment]
Oh the install location can very well be incorrect, but don't worry about that, just that it installs a 64 bit version correctly, which you can see as it installed the x64 dlls. You can also check the OpenHashTab.dll with any PE viewer to see it's also 64 bit.

**Comment by Neustradamus** [comment]
@namazso: Can you solve this installer issue?
- x64 -> "Program Files"
- x86 -> "Program Files (x86)"

**Comment by namazso** [comment]
Might look at it but it might just be a limitation of InnoSetup because it sees I have both 32 and 64 bit dlls in the same installer. However, considering it doesn't affect the operation of the program at all, I don't feel like this is too important.

Btw you can simply change the install location in the installer:

![image](https://user-images.githubusercontent.com/8676443/230798804-ac394318-d1c8-4ea4-bbf1-81e68a95e3cd.png)

**Comment by Neustradamus** [comment]
@namazso: Have you found the problem?

**Comment by namazso** [comment]
@Neustradamus This was fixed with https://github.com/namazso/OpenHashTab/commit/3abe557c2248c5602639c746906d5e6b05bb2e75 as part of removing 32-bit support entirely
