### ISSUE TITLE
8bit Hex value 01 repeated x 11468800 bytes file crashes Explorer when hashing it

### ISSUE THREAD

**Issue by ThePicMan** [namazso/OpenHashTab#174]
Hello,
windows Explorer crashes if I try to Hash a 11468800 bytes file where each, all and every byte is hex "01".

**Comment by ThePicMan** [comment]
[!!!!!This crashes Explorer when Hashing it.ZIP](https://github.com/namazso/OpenHashTab/files/11778856/This.crashes.Explorer.when.Hashing.it.ZIP)

**Comment by ThePicMan** [comment]
OpenHashTab v3.0.2

**Comment by namazso** [comment]
Stack overflow in sumfile matching regex, probably too much captures. Not exploitable, will try to replace it with a regex that doesn't do that.

**Comment by ThePicMan** [comment]
Thank you, keep the great work, I appreciate it, it's a very handy tool.

**Comment by namazso** [comment]
So the problem here is the SVF file matcher: SVF files are pretty bad because the file name (which may contain spaces) comes first, followed by whitespace, then the hash. this means that it can only be matched with greedy matchers, since we never know which space is the one we're looking for. I don't think I can solve this in regex, so it seems like I'll have to process these in code instead.
