### ISSUE TITLE
Error computing hashes for files on windows share

### ISSUE THREAD

**Issue by wsotest** [namazso/OpenHashTab#18]
OpenHashTab correctly calculate hashes for local files also for files on windows share mounted as drive.
But can't calculate hashes for files with path like: \\\192.168.1.100\Distrib\\*
When I open explorer with that path, select one file and goto Properties -> Hashes, I've got error message:
Algorithm | Hash
Error           The filename, directory name, or volume label syntax is incorrect

**Comment by namazso** [comment]
I'll look into this soon, it's supposed to handle any paths that explorer handles well (ie properties show correct data for).
Maybe this is because long path support... Windows removes a bit more than a simple limit there. Still, at worst I can just spam the various possible paths and see if winapi likes one.

I'm not exactly sure if sumfiles can be handled great though, because there are some extra security checks there about whether I opened the file the sumfile belongs to.

**Comment by namazso** [comment]
Well, better later than never. Newest release should be able to handle this.

**Comment by trockenasche** [comment]
In deed, it works now. Thanks!
