### ISSUE TITLE
VirusTotal check doesn't support non-ASCII filenames

### ISSUE THREAD

**Issue by zinalili** [namazso/OpenHashTab#187]
Every time I click on VirusTotal icon, Windows Explorer restarts.
Windows 10 22H2
OpenHashTab 3.0.4.0

**Comment by namazso** [comment]
Hm, works on my machine.

Can you reproduce it on the standalone version? Just export hashes, then double-click the file, that will open the standalone version.

If you can, then install [procdump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump) with `procdump -i C:\my\dumps\folder -mt` (with a path where you have write rights to) and get the standalone version to crash. A .dmp should appear in the folder, please send that to me by email. It is a triage level dump which should contain minimal personal information, but it will probably contain things like the file you're attempting to scan.

**Comment by namazso** [comment]
Okay, I think I figured it out. This happens when formatting the query string fails, which occurs when the file name contains characters that cannot be represented in your system locale. In that case `_vscprintf` returns -1, and we try to resize the string to (size_t)-1 long, also known as 18446744073709551615. Of course that results in "string too long" exception, which is uncaught, resulting in a crash.
