### ISSUE TITLE
Massive size increase between bc5897e and ac07e73? <3mb to >10mb

### ISSUE THREAD

**Issue by Darthagnon** [namazso/OpenHashTab#196]
Older versions of OpenHashTab were tiny, e.g. [ac07e73](https://github.com/namazso/OpenHashTab/commit/ac07e739b12faaf3d768fd7fe406f50ab11677f0) was [4.11mb](https://github.com/namazso/OpenHashTab/actions/runs/5562315246), v3.0.2 was [2.96mb](https://github.com/namazso/OpenHashTab/releases/tag/v3.0.2), then newer versions dropped features like 32-bit support and also massively increased in size, e.g. [bc5897e](https://github.com/namazso/OpenHashTab/commit/bc5897e99d86ffda6a0dbb760e4ebca8e2266dd5) was [10.2mb](https://github.com/namazso/OpenHashTab/actions/runs/5562378240) and all the latest versions [v3.0.3](https://github.com/namazso/OpenHashTab/releases/tag/v3.0.3) and up are also 10.2mb, while threatening to drop features like [old Windows support](https://github.com/namazso/OpenHashTab/issues/190).

I know it's still a tiny program, but why is it increasing almost 350% in size while dropping older Windows versions and 32bit processors? Seems counter-intuitive, less features should mean smaller size.

**Comment by namazso** [comment]
There are two major contributors to size:

- PDBs (debug information) that I include so that anyone can debug crashes of the released builds, without rebuilding it themselves
- Static linked CRT. This means a large part of the C runtime is linked into every dll and exe. This is so that people don't have to manually install the Visual C++ runtime. I could shave that off, resulting in much smaller binaries, but then I'd have to include the VC redistributable installer (25 MB), ultimately increasing the bundle size.

**Comment by Darthagnon** [comment]
Thank you very much for the info!

**Comment by mooms06** [comment]
> * but then I'd have to include the VC redistributable installer (25 MB), ultimately increasing the bundle size.

You could make the installer download/open a page to download them if they're not installed, but most systems already have those installed. I personally use @abbodi1406 repack: https://github.com/abbodi1406/vcredist
