### ISSUE TITLE
Use sans serif font for Chinese

### ISSUE THREAD

**Issue by Dothion** [namazso/OpenHashTab#20]
This software is using a serif font to display Chinese, which does not match the overall OS font. A sans serif font, such as Microsoft YaHei (微软雅黑), should be better.
![image](https://user-images.githubusercontent.com/31262977/83238157-9d21f180-a1c8-11ea-926e-5fcdbcd94d1d.png)

**Comment by namazso** [comment]
I don't know what happened there, I don't think I set fonts anywhere.
still, there seems to be a suspicious line in the dialog [here](https://github.com/namazso/OpenHashTab/blob/master/OpenHashTab/OpenHashTab.rc#L33), although this should just set whatever is default according to windows.

Maybe it's because translated strings are applied later, and it picks up whatever font is used for english.

i'll check this out soon
