### ISSUE TITLE
Right Margin Visual Glitch

### ISSUE THREAD

**Issue by meatflavourdev** [namazso/OpenHashTab#29]
There appears to be a visual glitch where the input group doesn't stretch to accommodate other window sizes.

![hash](https://user-images.githubusercontent.com/13112048/96412112-6e6bde00-119e-11eb-819f-24666b999d77.PNG)

_Windows 10 (2004) - build 19041.572_

**Comment by namazso** [comment]
This happens to some builtin windows property sheet pages too. This is because the whole thing sucks. If you want any kind of adaption to size whatsoever, you have to manually calculate the sizes of **every single element** in code because it does not honor automatic resize options. So yes, I do know of this bug, but I was too disgusted to fix it. I'll check if there's some marginally less insane solution to this.

**Comment by namazso** [comment]
fixed in 62f38e94b780da68c60c36b673aea3038e260d37
