### ISSUE TITLE
Request: auto read clipboard for compare & auto select algorithm

### ISSUE THREAD

**Issue by nkh0472** [namazso/OpenHashTab#37]
"Auto select algorithm" means to guess algorithm based on length of hash in clipboard.

**Comment by nkh0472** [comment]
Look at here, this project has implemented the feature I mentioned.  https://github.com/emoacht/HashPad

**Comment by namazso** [comment]
not sure why but that program doesn't seem to run on my VM:
![image](https://user-images.githubusercontent.com/8676443/101204619-c71f0980-366c-11eb-89a7-5ddaf47a9fe7.png)

Anyways, whenever you have a hash on your clipboad, it is automatically pasted into the find window and searched for in all hashes, so that's pretty much the behavior already as long as you have the given algorithm enabled.

Or did you mean it so that whenever a hash is found on clipboard it should automatically enable algorithms of that length? In that case, I could probably do that however considering we have SHA3 in 3 different lengths with terrible performance auto-enabling those when not needed might be a really bad idea.

**Comment by nkh0472** [comment]
> Or did you mean it so that whenever a hash is found on clipboard it should automatically enable algorithms of that length?

That's it.

>not sure why but that program doesn't seem to run on my VM

I'm not sure why it couldn't work. Actually, I'm using your software, so I didn't buy HashPad from Microsoft Store (and I didn't install complier so I can't compile it myself).
However, the author of that project mentioned he has already implemented the function I said: 
https://github.com/emoacht/HashPad/issues/4#issuecomment-731976528

>however considering we have SHA3 in 3 different lengths with terrible performance auto-enabling those when not needed might be a really bad idea

For SHA3, maybe give a popup window to select?

**Comment by namazso** [comment]
> However, the author of that project mentioned he has already implemented the function I said:

Easy for them, they carry one algorithm of each length. Say, you have a 256 bit hash on clipboard. That'd need to enable SHA-256, Blake2sp, SHA3-256, BLAKE3 here.

> For SHA3, maybe give a popup window to select?

I just picked SHA3 as an example really because its performance is really awful compared to others, but even in general if you have a BLAKE3 hash (throughput of 3 GB/s on my machine) you probably wouldn't want to waste time calculating even SHA-256 (throughput of 200 MB/s on my machine).

I guess I could add a popup enabled by a setting, asking you to select the algorithm, but it'd really remove simplicity. Plus it's a whole new dialog, making those in win32 is painful. In dev builds you can simply cancel, select algorithms needed, then re-open anyways.

**Comment by nkh0472** [comment]
LOL, if it is too hard to implement, forget about it!
 "Cancel" is enough for use.

**Comment by namazso** [comment]
Not long ago I made algorithms modifiable (programmatically, not for the user) during initialization for allowing algorithm auto-enable for sumfiles based on extension. That made implementing this much easier.

By default it's only enabled for when no algorithms of matching length are selected, to prevent users from accidentally causing performance problems:

![image](https://user-images.githubusercontent.com/8676443/101976391-0fc65c00-3c45-11eb-9874-fa16e067d3e8.png)
