### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Darthagnon** [namazso/OpenHashTab#46]
I speak PtBr as a 2nd language (Dad's Brazilian) and Spanish as a 3rd. I grew up reading Spanish computer magazines (Computer Hoy!, etc.), but have used Google.es and Google Translate to help, since tech jargon doesn't come naturally to me in foreign languages.

I will attempt to contribute via [Weblate](https://hosted.weblate.org/projects/openhashtab/main/es/)

Some notes:

- "Sumfile" has no direct translation afaik. I have used "archivo de comprobación" (literally, "check file", since sumfile = checksumfile)
- "hashes" is a valid English loanword, according to Spanish tech sites I've seen

**Comment by namazso** [comment]
Weblate can help you a lot with automatically offered google translate, ms translate and other projects' translations. That's pretty much how i translated to german, just asked someone to review it quick.
If you can verify that whatever it translates is valid it's good enough. It just sometimes messes up articles, possessive, etc.. usual translation stuff. Anyways, borrowed words are fine, probably whoever uses tihs program understands them, it's not like people who dont know what a hash is will need to understand whats written there.
Also, be aware of space limitations, overlong translations may cause UI problems. Just using english borrow-words might make more sense sometimes.
Also, i'd prefer if "sumfile" / "sum-file" would mostly stay that way, because it refers to the actual programs (md5sum, sha1sum, sha256sum) originally. If it sounds too foreign for a language it's fine if it changes ofc.

**Comment by Darthagnon** [comment]
Sounds good. I'd prefer to find a shorter term to "archivo de comprobación", too - I would use sumfile, but in Spanish it would come out pronounced "soom-feeleh" or "soom-fayyal" which sounds weird, considering they use "archivo" for "file" (and "carpeta" for folder). 

Maybe "archivo de sum" or "sumarchivo" could work...

**Comment by Darthagnon** [comment]
Question: Isn't the English  "sumfile" an artificial word? Would it be better to use ```checksum``` or ```hashes``` instead? It would do away with this translation problem. I've seen other projects using both "checksum" and "hashes" to refer to both the long strings of numbers/letters and to txt files containing them.

**Comment by Darthagnon** [comment]
Not too sure about ```compilaciones de desarrollo``` for ```development builds``` but am not familiar enough with the Spanish part of the internet to find a tech article talking about them.

**Comment by namazso** [comment]
>Isn't the English "sumfile" an artificial word? 
it is.

>Would it be better to use checksum or hashes instead? 
this is what i meant by maybe i should reconsider wording. originally it was called sumfile because it explicitly referred to those family of programs (md5sum, sha1sum, sha256sum) and not just any generic hash collection file format. This is changing now with partial SFV support and corz .hash support though. 

>I think I've done all I can on the Spanish translation for the moment; gonna need a native Spanish techy/programmer familiar with the correct terms to double-check.
Thanks. It's a crowd translation platform for a reason after all, any non-zero cotribution is more than anyone is expected to make.

**Comment by Darthagnon** [comment]
Just thought I'd post back here - while I was at it, went and did Brazilian Portuguese, too. Should be the same as regular Pt, would only make a difference for e.g. books/movies/long stories
