### ISSUE TITLE
Feature Request: Add option for Blake3-512

### ISSUE THREAD

**Issue by tERyceNzAchE** [namazso/OpenHashTab#56]
Add option to create Blake3-512 hashes.

**Comment by namazso** [comment]
Is it used anywhere relevant? algorithms like BLAKE3 and several others from the XKCP have user-defined output sizes. Since the current code really doesn't support exposing this as an option to the user, only the default sizes are added (since they are the ones used practically everywhere), which is 256 bits for BLAKE3.

**Comment by tERyceNzAchE** [comment]
Blake3-512 is pretty common.  Uses for sizes other than 256 and 512 are pretty rare.
I would suggest keeping the current implementation as-is, and adding an option for BLAKE3-512 (much like for SHA).

**Comment by divinity76** [comment]
> Is it used anywhere relevant? 

[is 512 bits even useful?](https://github.com/sahib/rmlint/issues/424#issuecomment-825243752)
