### ISSUE TITLE
How to set up Simplified Chinese?

### ISSUE THREAD

**Issue by NieLnchn** [namazso/OpenHashTab#6]
I saw support for Simplified Chinese in Readme, but I didn't find him.
Thank you.

**Comment by namazso** [comment]
It should automatically adapt to your system language, like this screenshot on a Hungarian Windows install:
![image](https://user-images.githubusercontent.com/8676443/77019161-338f9680-6980-11ea-998c-5e09f47bc4f5.png)

**Comment by namazso** [comment]
*on a second thought, it seems like I (probably incorrectly) have it tagged as traditional chinese sublang: https://github.com/namazso/OpenHashTab/blob/master/OpenHashTab/OpenHashTab.rc#L23
though because of the lack of a simplified chinese version this should still be preferred by chinese windows over the english one.

**Comment by namazso** [comment]
you're right, it doesn't use correct language for some reason.

**Comment by namazso** [comment]
fix will be available in next release:
![image](https://user-images.githubusercontent.com/8676443/77021834-32fafe00-6988-11ea-869c-0953af26c9f1.png)
