### ISSUE TITLE
OpenHashTab hang on folders with large number of files

### ISSUE THREAD

**Issue by Nico207** [namazso/OpenHashTab#76]
Hi,

I've tried to check sum on a folder with +21000 files (+32Go).
It works, but on start, the properties window doesn't respond for a long time

![image](https://user-images.githubusercontent.com/1179972/113153544-7f357b00-9237-11eb-978e-a7c01cc77404.png)
![image](https://user-images.githubusercontent.com/1179972/113153056-020a0600-9237-11eb-88cd-9716d8eccebc.png)
![image](https://user-images.githubusercontent.com/1179972/113153093-0cc49b00-9237-11eb-9212-8b78ff1246c6.png)

**Comment by Nico207** [comment]
If you ask to add +20000 lines on a loop, one at a time, I understand why windows hang 😁 
Maybe:

- Forcing a redraw from time to time ?
- Leave the hand to the display process to give it time to do its job ?
- Do not display the list during the filling process and only display it at the end ?

(it's proposals thrown out like that, in truth I don't know what is possible to do or not in C)

**Comment by namazso** [comment]
> If you ask to add +20000 lines on a loop, one at a time, I understand why windows hang

A loop like that would probably be better. Currently the hashing threadpool pushes out window notifications whenever a job is done (sometimes really fast). The dialog window picks this up and adds the results to the list. The list then, feeling that something was added will invalidate its client area, forcing a repaint.

> Forcing a redraw from time to time ?

Unfortunately i can't make the listview swallow its invalidations

> Leave the hand to the display process to give it time to do its job ?

That's the plan, just queue added stuff in a local buffer, then add them in a loop every time we get a percentage notification (special notifications are sent each percent of data processed, to display the bottom progress bar). Hopefully this way we can just batch the useless invalidations, and let enough time pass for one paint to complete before a new invalidation.

> Do not display the list during the filling process and only display it at the end ?

Might be a good idea, after all the whole window is rather useless until processing has finished. If the percentage solution doesn't work i will probably do this. Maybe even make it click-to-display since for so many files usually you'd only want to see either match count or export results, none of which needs the display.

**Comment by namazso** [comment]
for now i just add them only at the finish. I'm not sure how much this improves speed, but at least less locking should happen now.

**Comment by VsevolodGolovanov** [comment]
Still locks up first with a large folder. I guess while it discovers folder contents?
When opening a checksum file the OpenHashTab window also takes a while to show up.
