### ISSUE TITLE
Please add GPU acceleration

### ISSUE THREAD

**Issue by mrdavidmiller** [namazso/OpenHashTab#78]
null

**Comment by namazso** [comment]
Most usage cases wouldn't significantly benefit from this. What are you doing that you think GPU acceleration would solve?

**Comment by mrdavidmiller** [comment]
I’m a YouTuber’s editor. Our team is using your software. It takes a long time to calculate a hash which is over 20 Gib. I think it’s more convenient to have GPU acceleration.

**Comment by namazso** [comment]
I don't think you realize hash calculation of a single file is a sequential operation, and that single thread performance on a GPU is much worse. Let's assume a single thread of a GPU is only 10 times slower than a single thread of a CPU, and that you have an 8 core CPU. This would mean that GPU hashing would only benefit you if you would be hashing 80 files at a time at least. Considering it's videos you are speaking of, I am assuming this is not the case, since 250 MB per video would be rather small.

**Comment by namazso** [comment]
I guess there are two exceptions, KangarooTwelve and ParallelHash are capable of hashing parallel, however I cannot find an OpenCL / CUDA implementation for either.

**Comment by mrdavidmiller** [comment]
Thanks
