### ISSUE TITLE
problem with checking XXH3-64

### ISSUE THREAD

**Issue by g0blin-NN** [namazso/OpenHashTab#81]
create
![Clipboard01](https://user-images.githubusercontent.com/66860852/122074122-9f6de280-ce01-11eb-94ab-1e24fbb1efb9.png)
checking (double click on a file `ventoy-1.0.46-windows.zip.xxh3-64`)
![Clipboard02](https://user-images.githubusercontent.com/66860852/122074282-bf9da180-ce01-11eb-994f-792e3a5d9b3f.png)
why not green?
file contents `ventoy-1.0.46-windows.zip.xxh3-64`:
`d402a84ee753a4bd *ventoy-1.0.46-windows.zip`
https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-windows.zip

**Comment by namazso** [comment]
because XXHash is not a cryptographically secure algorithm, which is marked brown. works as intended

**Comment by g0blin-NN** [comment]
@namazso ok. it is not clear whether the checksum is correct, if it is incorrectly red? 
corrected the last symbol in the editor, see what happens ...
![Clipboard01](https://user-images.githubusercontent.com/66860852/122080724-2d989780-ce07-11eb-92a3-cdbc24b97097.png)
why is everything red? I only checked XXH3-64

**Comment by namazso** [comment]
correct, red is mismatch, brown is insecure, green is match, white is nothing to match against, and red text on white is unreadable (os returned error when opening / reading)

and everything is red since none matches. the program has no clue it was intended to be an xxh3 hash, it just knows none of the calculated ones match the found value
